name: gala

channels:
  - astropy

dependencies:
  - python==3.6
  - astropy>=3
  - astropy-helpers
  - numpy
  - cython
  - matplotlib
  - scipy
  - pyyaml
  - IPython
  - jupyter
  - notebook
  - ipykernel
  - pip:
    - nbsphinx==0.3.1
