# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows

environment:

  global:
      PYTHON: "C:\\conda"
      MINICONDA_VERSION: "latest"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.

      # For this package-template, we include examples of Cython modules,
      # so Cython is required for testing. If your package does not include
      # Cython code, you can set CONDA_DEPENDENCIES=''
      CONDA_DEPENDENCIES: "Cython scipy matplotlib pyyaml sympy"

      # Conda packages for affiliated packages are hosted in channel
      # "astropy" while builds for astropy LTS with recent numpy versions
      # are in astropy-ci-extras. If your package uses either of these,
      # add the channels to CONDA_CHANNELS along with any other channels
      # you want to use.
      # CONDA_CHANNELS: "astopy-ci-extras astropy"

  matrix:

      # We test Python 2.7 and 3.5 because 2.7 is the supported Python 2
      # release of Astropy and Python 3.5 is the latest Python 3 release.

      - PYTHON_VERSION: "2.7"
        ASTROPY_VERSION: "stable"
        NUMPY_VERSION: "stable"

      - PYTHON_VERSION: "3.5"
        ASTROPY_VERSION: "stable"
        NUMPY_VERSION: "stable"

platform:
    -x64

install:
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"

# Not a .NET project, we build the package in the install step instead
build: false

test_script:
    - "%CMD_IN_ENV% python setup.py test"
